import React, { createContext, useContext, useState, useEffect } from "react";

const AppSettingsContext = createContext(null);

// Compact multilingual dictionary for UI strings. Keys are used across all pages.
const TRANSLATIONS = {
  en: {
    appName: "Kabiru AI Tutor",
    dashboard: "Dashboard",
    courses: "Courses",
    aiChat: "AI Chat",
    progress: "Progress",
    certificates: "Certificates",
    notes: "Notes",
    settings: "Settings",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    continueLearning: "Continue Learning",
    yourProgress: "Your Progress",
    streak: "Day Streak",
    searchLessons: "Search lessons...",
    startLesson: "Start Lesson",
    completeLesson: "Mark as Complete",
    takeQuiz: "Take Quiz",
    submitQuiz: "Submit Quiz",
    explanation: "Explanation",
    examples: "Examples",
    practice: "Practice",
    miniProject: "Mini Project",
    realWorldProject: "Real-World Project",
    commonMistakes: "Common Mistakes",
    bestPractices: "Best Practices",
    interviewQuestions: "Interview Questions",
    assignment: "Assignment",
    challenge: "Challenge",
    summary: "Summary",
    references: "References",
    nextLessonPreview: "Next Lesson Preview",
    askTutor: "Ask your AI tutor anything...",
    send: "Send",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    language: "Language",
    getStarted: "Get Started",
    viewCertificate: "View Certificate",
    download: "Download",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    newNote: "New Note",
    noNotesYet: "No notes yet. Start writing!",
    checkMyCode: "Check My Code",
    yourCode: "Your Code (Python)",
    lessonLockedHint: "Complete the previous lesson and pass its quiz to unlock this one.",
  },
  ha: {
    appName: "Kabiru AI Tutor",
    dashboard: "Dashboard",
    courses: "Darussa",
    aiChat: "Tattaunawa da AI",
    progress: "Ci gaba",
    certificates: "Takardun shaida",
    notes: "Bayanai",
    settings: "Saitunan",
    login: "Shiga",
    register: "Yi rijista",
    logout: "Fita",
    email: "Imel",
    password: "Kalmar sirri",
    fullName: "Cikakken suna",
    welcomeBack: "Barka da dawowa",
    createAccount: "Kirkiri asusun ka",
    continueLearning: "Ci gaba da koyo",
    yourProgress: "Ci gabanka",
    streak: "Kwanaki a jere",
    searchLessons: "Nemo darasi...",
    startLesson: "Fara Darasi",
    completeLesson: "Kammala Darasi",
    takeQuiz: "Yi Jarrabawa",
    submitQuiz: "Mika Jarrabawa",
    explanation: "Bayani",
    examples: "Misalai",
    practice: "Aiki",
    miniProject: "Karamin Aiki",
    realWorldProject: "Aiki na Zahiri",
    commonMistakes: "Kurakurai na Kowa",
    bestPractices: "Hanyoyin da Suka Fi Dacewa",
    interviewQuestions: "Tambayoyin Hira",
    assignment: "Aikin Gida",
    challenge: "Kalubale",
    summary: "Takaitawa",
    references: "Ambato",
    nextLessonPreview: "Gabatarwar Darasi Na Gaba",
    askTutor: "Tambayi malamin AI naka...",
    send: "Aika",
    darkMode: "Duhu",
    lightMode: "Haske",
    language: "Harshe",
    getStarted: "Fara",
    viewCertificate: "Duba Takardar shaida",
    download: "Sauke",
    save: "Ajiye",
    cancel: "Soke",
    delete: "Goge",
    newNote: "Sabon Bayani",
    noNotesYet: "Babu bayani tukuna. Fara rubutu!",
    checkMyCode: "Duba Code Dina",
    yourCode: "Code Dinka (Python)",
    lessonLockedHint: "Kammala darasi na baya kuma ka ci jarabawarsa kafin ka bude wannan.",
  },
  fr: {
    appName: "Kabiru AI Tutor",
    dashboard: "Tableau de bord",
    courses: "Cours",
    aiChat: "Chat IA",
    progress: "Progression",
    certificates: "Certificats",
    notes: "Notes",
    settings: "Paramètres",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    email: "E-mail",
    password: "Mot de passe",
    fullName: "Nom complet",
    welcomeBack: "Content de vous revoir",
    createAccount: "Créez votre compte",
    continueLearning: "Continuer l'apprentissage",
    yourProgress: "Votre progression",
    streak: "Jours consécutifs",
    searchLessons: "Rechercher des leçons...",
    startLesson: "Commencer la leçon",
    completeLesson: "Marquer comme terminé",
    takeQuiz: "Passer le quiz",
    submitQuiz: "Soumettre le quiz",
    explanation: "Explication",
    examples: "Exemples",
    practice: "Pratique",
    miniProject: "Mini-projet",
    realWorldProject: "Projet concret",
    commonMistakes: "Erreurs courantes",
    bestPractices: "Bonnes pratiques",
    interviewQuestions: "Questions d'entretien",
    assignment: "Devoir",
    challenge: "Défi",
    summary: "Résumé",
    references: "Références",
    nextLessonPreview: "Aperçu de la leçon suivante",
    askTutor: "Posez une question à votre tuteur IA...",
    send: "Envoyer",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    language: "Langue",
    getStarted: "Commencer",
    viewCertificate: "Voir le certificat",
    download: "Télécharger",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    newNote: "Nouvelle note",
    noNotesYet: "Pas encore de notes. Commencez à écrire !",
    checkMyCode: "Vérifier mon code",
    yourCode: "Votre code (Python)",
    lessonLockedHint: "Terminez la leçon précédente et réussissez son quiz pour débloquer celle-ci.",
  },
  ar: {
    appName: "Kabiru AI Tutor",
    dashboard: "لوحة التحكم",
    courses: "الدورات",
    aiChat: "محادثة الذكاء الاصطناعي",
    progress: "التقدم",
    certificates: "الشهادات",
    notes: "الملاحظات",
    settings: "الإعدادات",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    fullName: "الاسم الكامل",
    welcomeBack: "مرحبًا بعودتك",
    createAccount: "أنشئ حسابك",
    continueLearning: "واصل التعلم",
    yourProgress: "تقدمك",
    streak: "أيام متتالية",
    searchLessons: "البحث عن الدروس...",
    startLesson: "ابدأ الدرس",
    completeLesson: "وضع علامة مكتمل",
    takeQuiz: "أجرِ الاختبار",
    submitQuiz: "إرسال الاختبار",
    explanation: "الشرح",
    examples: "أمثلة",
    practice: "تدريب",
    miniProject: "مشروع صغير",
    realWorldProject: "مشروع من الواقع",
    commonMistakes: "الأخطاء الشائعة",
    bestPractices: "أفضل الممارسات",
    interviewQuestions: "أسئلة المقابلة",
    assignment: "الواجب",
    challenge: "تحدٍ",
    summary: "الملخص",
    references: "المراجع",
    nextLessonPreview: "معاينة الدرس التالي",
    askTutor: "اسأل معلمك الذكي أي شيء...",
    send: "إرسال",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    language: "اللغة",
    getStarted: "ابدأ الآن",
    viewCertificate: "عرض الشهادة",
    download: "تنزيل",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    newNote: "ملاحظة جديدة",
    noNotesYet: "لا توجد ملاحظات بعد. ابدأ الكتابة!",
    checkMyCode: "تحقق من الكود الخاص بي",
    yourCode: "الكود الخاص بك (Python)",
    lessonLockedHint: "أكمل الدرس السابق واجتز اختباره لفتح هذا الدرس.",
  },
};

// Ordered list of supported languages for <select> dropdowns across the app.
export const SUPPORTED_LANGUAGES = [
  { code: "en", label: "English" },
  { code: "ha", label: "Hausa" },
  { code: "fr", label: "Français" },
  { code: "ar", label: "العربية" },
];

export function AppSettingsProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem("kabiru_theme") || "light");
  const [language, setLanguage] = useState(() => localStorage.getItem("kabiru_language") || "en");

  useEffect(() => {
    const root = document.documentElement;
    if (theme === "dark") {
      root.classList.add("dark");
    } else {
      root.classList.remove("dark");
    }
    localStorage.setItem("kabiru_theme", theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem("kabiru_language", language);
  }, [language]);

  const toggleTheme = () => setTheme((t) => (t === "dark" ? "light" : "dark"));
  const toggleLanguage = () => setLanguage((l) => (l === "en" ? "ha" : "en"));

  const t = (key) => TRANSLATIONS[language]?.[key] ?? TRANSLATIONS.en[key] ?? key;

  return (
    <AppSettingsContext.Provider
      value={{ theme, setTheme, toggleTheme, language, setLanguage, toggleLanguage, t }}
    >
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const ctx = useContext(AppSettingsContext);
  if (!ctx) throw new Error("useAppSettings must be used within AppSettingsProvider");
  return ctx;
}
